### ISSUE TITLE
pdftk is not found solution

### ISSUE THREAD

**Issue by alezzacreative** [raniaamina/pdf-extractor#1]
hello am alezzacreative
pdftk is not found anymore in the ppa you provided : sudo add-apt-repository ppa:malteworld/ppa
the solution i did to install it is the folowing :
1- sudo apt install default-jre-headless libcommons-lang3-java libbcprov-java
2- download the deb file of pdftk-java from 
https://packages.ubuntu.com/focal/pdftk-java
3- download the deb file of pdftk from 
https://packages.ubuntu.com/focal/pdftk
and that fixed the problem

**Comment by raniaamina** [comment]
oh thank you @alezzacreative , i'll add your solution into readme, hope it will help other people out there

**Comment by alezzacreative** [comment]
thank you too and see you in the inkscape vector meeting
